# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/59/A
# 59A - Word

import sys
input = sys.stdin.readline

def solve():
    s = input().strip()
    print(s.lower() if sum(c.islower() for c in s) >= len(s)/2 else s.upper())

if __name__ == "__main__":
    solve() 