# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/546/A
# 546A - Soldier and Bananas

import sys
input = sys.stdin.readline

def solve():
    k, n, w = map(int, input().split())
    total = k * w * (w + 1) // 2
    print(max(0, total - n))

if __name__ == "__main__":
    solve() 