# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/977/A
# 977A - Wrong Subtraction

import sys
input = sys.stdin.readline

def solve():
    n, k = map(int, input().split())
    for _ in range(k):
        n = n - 1 if n % 10 else n // 10
    print(n)

if __name__ == "__main__":
    solve() 