# This code is generated by AI just for testing
# Using GPT-4-turbo

# https://codeforces.com/problemset/problem/344/A
# 344A - Magnets


import sys
input = sys.stdin.readline

def solve():
    n = int(input().strip())
    magnets = [input().strip() for _ in range(n)]
    
    groups = 1
    for i in range(1, n):
        if magnets[i] != magnets[i - 1]:
            groups += 1
    
    print(groups)

if __name__ == "__main__":
    solve()
