# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/112/A
# 112A - Petya and Strings

import sys
input = sys.stdin.readline

def solve():
    s1 = input().strip().lower()
    s2 = input().strip().lower()
    print((s1 > s2) - (s1 < s2))

if __name__ == "__main__":
    solve() 