# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/266/A
# 266A - Stones on the Table

import sys
input = sys.stdin.readline

def solve():
    n = int(input())
    s = input().strip()
    cnt = 0
    for i in range(n-1):
        if s[i] == s[i+1]:
            cnt += 1
    print(cnt)

if __name__ == "__main__":
    solve() 