# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/50/A
# 50A - Domino piling

import sys
input = sys.stdin.readline

def solve():
    m, n = map(int, input().split())
    print(m * n // 2)

if __name__ == "__main__":
    solve() 