# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/231/A
# 231A - Team

import sys
input = sys.stdin.readline

def solve():
    cnt = 0
    n = int(input())
    for _ in range(n):
        p, v, t = map(int, input().split())
        cnt += 1 if p + v + t >= 2 else 0
    print(cnt)

if __name__ == "__main__":
    solve() 