# This code is generated by AI just for testing
# Using GPT-4-turbo

# https://codeforces.com/problemset/problem/467/A
# 467A - George and Accommodation

import sys
input = sys.stdin.readline

def solve():
    n = int(input().strip())
    count = 0
    
    for _ in range(n):
        p, q = map(int, input().split())
        if q - p >= 2:
            count += 1
    
    print(count)

if __name__ == "__main__":
    solve()

