# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/118/A
# 118A - String Task

import sys
input = sys.stdin.readline

def solve():
    s = input().strip().lower()
    vowels = set('aeiouy')
    result = []
    for c in s:
        if c not in vowels:
            result.extend(['.', c])
    print(''.join(result))

if __name__ == "__main__":
    solve() 