# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/110/A
# 110A - Nearly Lucky Number

import sys
input = sys.stdin.readline

def solve():
    s = input().strip()
    count = sum(1 for d in s if d in '47')
    print('YES' if str(count) in {'4', '7', '44', '47', '74', '77', '444', '447', '474', '477', '744', '747', '774', '777'} else 'NO')

if __name__ == "__main__":
    solve()