# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/281/A
# 281A - Word Capitalization

import sys
input = sys.stdin.readline

def solve():
    s = input().strip()
    print(s[0].upper() + s[1:])

if __name__ == "__main__":
    solve() 