# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/734/A
# 734A - Anton and Danik

import sys
input = sys.stdin.readline

def solve():
    n = int(input())
    s = input().strip()
    a = s.count('A')
    print("Anton" if a > n-a else "Danik" if a < n-a else "Friendship")

if __name__ == "__main__":
    solve() 