# This code is generated by AI just for testing
# Using GPT-4-turbo

# https://codeforces.com/problemset/problem/1030/A
# 1030A - In Search of an Easy Problem

import sys
input = sys.stdin.readline

def solve():
    n = int(input().strip())
    opinions = list(map(int, input().split()))
    
    if 1 in opinions:
        print("HARD")
    else:
        print("EASY")

if __name__ == "__main__":
    solve()