# This code is generated by AI just for testing
# Using DeepSeek-V3

# https://oj.vnoi.info/problem/post
# A plus B


def solve():
    # Read input
    A, B = map(int, input().split())

    # Calculate sum
    sum = A + B

    # Output the result
    print(sum)

if __name__ == "__main__":
    solve() 
