# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/791/A
# 791A - Bear and Big Brother

import sys
input = sys.stdin.readline

def solve():
    a, b = map(int, input().split())
    years = 0
    while a <= b:
        a *= 3
        b *= 2
        years += 1
    print(years)

if __name__ == "__main__":
    solve() 