# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/158/A
# 158A - Next Round

import sys
input = sys.stdin.readline

def solve():
    n, k = map(int, input().split())
    scores = list(map(int, input().split()))
    k_score = scores[k-1]
    cnt = 0
    for s in scores:
        if s > 0 and s >= k_score:
            cnt += 1
    print(cnt)

if __name__ == "__main__":
    solve() 