# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/71/A
# 71A - Way Too Long Words

import sys
input = sys.stdin.readline

def solve():
    s = input().strip()
    print(s if len(s) <= 10 else f"{s[0]}{len(s)-2}{s[-1]}")

if __name__ == "__main__":
    t = int(input())
    for _ in range(t):
        solve() 