# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/1/A
# 1A - Theatre Square

import sys
input = sys.stdin.readline

def solve():
    n, m, a = map(int, input().split())
    x = (n + a - 1) // a
    y = (m + a - 1) // a
    print(x * y)

if __name__ == "__main__":
    solve() 