# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/271/A
# 271A - Beautiful Year

import sys
input = sys.stdin.readline

def solve():
    y = int(input())
    while True:
        y += 1
        if len(set(str(y))) == 4:
            print(y)
            break

if __name__ == "__main__":
    solve()