# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/4/A
# 4A - Watermelon


import sys
input = sys.stdin.readline

def solve():
    w = int(input())
    print("YES" if w > 2 and w % 2 == 0 else "NO")

if __name__ == "__main__":
    solve() 