# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/486/A
# 486A - Calculating Function

import sys
input = sys.stdin.readline

def solve():
    n = int(input().strip())
    
    if n % 2 == 0:
        print(n // 2)
    else:
        print(-((n // 2) + 1))

if __name__ == "__main__":
    solve()