# This code is generated by AI just for testing
# Using GPT-4-turbo

# https://codeforces.com/problemset/problem/58/A
# 58A - Chat Room

import sys
input = sys.stdin.readline

def solve():
    s = input().strip()
    target = "hello"
    j = 0
    
    for char in s:
        if char == target[j]:
            j += 1
            if j == len(target):
                print("YES")
                return
    
    print("NO")

if __name__ == "__main__":
    solve()
