# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/263/A
# 263A - Beautiful Matrix

import sys
input = sys.stdin.readline

def solve():
    for i in range(5):
        row = list(map(int, input().split()))
        if 1 in row:
            j = row.index(1)
            print(abs(i - 2) + abs(j - 2))
            return

if __name__ == "__main__":
    solve() 