# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/116/A
# 116A - Tram

import sys
input = sys.stdin.readline

def solve():
    n = int(input())
    curr = max_p = 0
    for _ in range(n):
        a, b = map(int, input().split())
        curr = curr - a + b
        max_p = max(max_p, curr)
    print(max_p)

if __name__ == "__main__":
    solve()