# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/96/A
# 96A - Football

import sys
input = sys.stdin.readline

def solve():
    s = input().strip()
    print("YES" if "0000000" in s or "1111111" in s else "NO")

if __name__ == "__main__":
    solve() 