# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/69/A
# 69A - Young Physicist

import sys
input = sys.stdin.readline

def solve():
    n = int(input())
    x = y = z = 0
    for _ in range(n):
        xi, yi, zi = map(int, input().split())
        x += xi
        y += yi
        z += zi
    print("YES" if x == y == z == 0 else "NO")

if __name__ == "__main__":
    solve() 