# This code is generated by AI just for testing
# Using claude-3.5-sonnet
 
# https://codeforces.com/problemset/problem/677/A
# 677A - Vanya and Fence
 
import sys
input = sys.stdin.readline
 
def solve():
    n, h = map(int, input().split())
    a = map(int, input().split())
    print(sum(2 if x > h else 1 for x in a))
 
if __name__ == "__main__":
    solve()