# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/617/A
# 617A - Elephant

import sys
input = sys.stdin.readline

def solve():
    x = int(input())
    print((x + 4) // 5)

if __name__ == "__main__":
    solve() 