# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/339/A
# 339A - Helpful Maths

import sys
input = sys.stdin.readline

def solve():
    s = input().strip()
    nums = sorted(s[::2])
    print('+'.join(nums))

if __name__ == "__main__":
    solve() 