# This code is generated by AI just for testing
# Using claude-3.5-sonnet

# https://codeforces.com/problemset/problem/236/A
# 236A - Boy or Girl

import sys
input = sys.stdin.readline

def solve():
    s = input().strip()
    print("CHAT WITH HER!" if len(set(s)) % 2 == 0 else "IGNORE HIM!")

if __name__ == "__main__":
    solve() 