# This code is generated by AI just for testing
# Using GPT-4-turbo

# https://codeforces.com/problemset/problem/266/B
# 266B - Queue at the School

import sys
input = sys.stdin.readline

def solve():
    n, t = map(int, input().split())
    s = list(input().strip())
    
    for _ in range(t):
        i = 0
        while i < len(s) - 1:
            if s[i] == 'B' and s[i + 1] == 'G':
                s[i], s[i + 1] = s[i + 1], s[i]
                i += 1
            i += 1
    
    print("".join(s))

if __name__ == "__main__":
    solve()